controller: NINTENDO_NES_CONTROLLER
name: "Default NES Mapping"
mapping:
    NES_DPAD_UP: GAMEPAD_DPAD_UP
    NES_DPAD_DOWN: GAMEPAD_DPAD_DOWN
    NES_DPAD_LEFT: GAMEPAD_DPAD_LEFT
    NES_DPAD_RIGHT: GAMEPAD_DPAD_RIGHT
    NES_START: GAMEPAD_START
    NES_SELECT: GAMEPAD_SELECT
    NES_A: GAMEPAD_A
    NES_B: GAMEPAD_B
