language: csharp
sudo: required
solution: Snowflake.sln
mono: none
dotnet: 2.0.0
dist: trusty 
group: deprecated-2017Q4
osx_image: xcode8.3
os:
  - linux
  - osx
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
install:
  - dotnet restore src/Snowflake.sln
  
script:
  - dotnet build src/Snowflake.Framework.Tests
  - dotnet test src/Snowflake.Framework.Tests/Snowflake.Framework.Tests.csproj
