language: csharp
sudo: false
solution: Snowflake.sln
mono:
  - 4.2.2
install:
  - nuget restore ./Snowflake.sln
 
addons:
  coverity_scan:
    project:
      name: "SnowflakePowered/snowflake"
      description: "Build submitted via Travis CI"
    notification_email: ronny6993@gmail.com
    build_command: "xbuild /p:Configuration=Debug Snowflake.sln /p:TargetFrameworkVersion=\"v4.5\""
    branch_pattern: master
    
script:
  -  xbuild /p:Configuration=Debug Snowflake.sln /p:TargetFrameworkVersion="v4.5"
  
notifications:
  irc:
    channels:
      - "irc.stormbit.net#snowflake"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: true
  webhooks: http://fure-kun.herokuapp.com/hubot/travis?room=%23snowflake
