language: csharp
solution: Snowflake.sln
install:
  - sudo mozroots --import --sync
  - ls
  - mono ./.nuget/NuGet.exe update -self
  - mono ./.nuget/NuGet.exe restore Snowflake.sln
script:
  - xbuild /p:Configuration=Debug Snowflake.sln
notifications:
  irc:
    channels:
      - "irc.stormbit.net#snowflake"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: true
  webhooks: http://fure-kun.herokuapp.com/hubot/travis?room=%23snowflake
