# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

variables:
  BUILD_NUMBER: '$(Build.BuildNumber)'
  STAGING: '$(Build.ArtifactStagingDirectory)'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: azure-setup.yml  # Template reference

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: azure-setup.yml # Template reference
  - pwsh: |
      codecov -f "$(System.DefaultWorkingDirectory)/src/Snowflake.Framework.Tests/coverage.opencover.xml" -t $env:CODECOV_TOKEN -sha $(Build.SourceVersion)
    workingDirectory: "$(System.DefaultWorkingDirectory)"
    displayName: Publishing test coverage to Codecov 
    env:
      CODECOV_TOKEN: $(codecov.secretToken)

  - task: PublishCodeCoverageResults@1
    displayName: Publshing test coverage to Azure
    inputs:
      codeCoverageTool: 'cobertura' # Options: cobertura, jaCoCo
      summaryFileLocation: $(System.DefaultWorkingDirectory)/src/Snowflake.Framework.Tests/coverage.cobertura.xml

  - task: PublishBuildArtifacts@1
    displayName: Publishing build artifacts
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'drop'