# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

name: $(Date:yyyyMMdd)$(Rev:rrrr)

trigger:
- master

variables:
  BUILD_NUMBER: '$(Build.BuildNumber)'
  STAGING: '$(Build.ArtifactStagingDirectory)'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  # - task: DotNetCoreInstaller@0
  #   displayName: Installing .NET Core 3 SDK
  #   inputs:
  #     packageType: 'sdk' # Options: runtime, sdk
  #     version: '3.0.100-preview3-010431' 
  # - bash: |
  #    wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
  #    sudo dpkg -i packages-microsoft-prod.deb
  #    sudo apt-get install apt-transport-https
  #    sudo apt-get update
  #    sudo apt-get install dotnet-sdk-2.2
  #    sudo apt-get install dotnet-sdk-2.1
  #   displayName: Manually install .NET Core 2.2 SDK
  - template: azure-setup.yml  # Template reference

  - script: |
      export PATH=$HOME/.dotnet/tools:$PATH
      nuke ContinuousIntegration
    displayName: Build and package framework and modules.
  
 - task: PublishTestResults@2
    displayName: Publish test results to Azure
    inputs:
      testResultsFormat: 'VSTest' 
      testResultsFiles: '*.trx' 
      searchFolder: '$(System.DefaultWorkingDirectory)/src/Snowflake.Framework.Tests/TestResults'

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: DotNetCoreInstaller@0
    displayName: Installing .NET Core 3 SDK
    inputs:
      packageType: 'sdk' # Options: runtime, sdk
      version: '3.0.100-preview3-010431' 
  - template: azure-setup.yml # Template reference
  
  - script: |
      export PATH=$HOME/.dotnet/tools:$PATH
      nuke ContinuousIntegration
    displayName: Build and package framework and modules.
    
  - task: PublishTestResults@2
    displayName: Publish test results to Azure
    inputs:
      testResultsFormat: 'VSTest' 
      testResultsFiles: '*.trx' 
      searchFolder: '$(System.DefaultWorkingDirectory)/src/Snowflake.Framework.Tests/TestResults'

  - pwsh: |
      codecov -f "$(System.DefaultWorkingDirectory)/src/Snowflake.Framework.Tests/coverage.opencover.xml" -t $(CODECOV_TOKEN) --sha $(Build.SourceVersion) --build $(Build.BuildNumber)
    workingDirectory: "$(System.DefaultWorkingDirectory)"
    displayName: Publishing test coverage to Codecov 
    env:
      CODECOV_TOKEN: $(codecov.secretToken)

  - task: PublishCodeCoverageResults@1
    displayName: Publshing test coverage to Azure
    inputs:
      codeCoverageTool: 'cobertura' # Options: cobertura, jaCoCo
      summaryFileLocation: $(System.DefaultWorkingDirectory)/src/Snowflake.Framework.Tests/coverage.cobertura.xml

  - task: PublishBuildArtifacts@1
    displayName: Publishing build artifacts
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'drop'