# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  BUILD_NUMBER: '$(Build.BuildNumber)'
  STAGING: '$(Build.ArtifactStagingDirectory)'

steps:
- task: DotNetCoreInstaller@0
  displayName: Installing .NET Core CLI
  inputs:
    packageType: 'sdk' # Options: runtime, sdk
    version: '3.0.100-preview3-010431' 

- task: NuGetToolInstaller@0
  displayName: Installing NuGet CLI

- script: |
    dotnet tool install --global Codecov.Tool --version 1.3.0	
  displayName: Install Codecov Tool

- script: |
    dotnet tool install Nuke.GlobalTool --global
  displayName: Install NUKE CLI

- script: |
    nuke ContinuousIntegration
  displayName: Build and package framework and modules.

      
- task: VSTest@2
  displayName: Testing for Azure Test Coverage
  inputs:
    testSelector: 'testAssemblies' # Options: testAssemblies, testPlan, testRun
    testAssemblyVer2: '**\Snowflake.Framework.Tests.dll!**\obj\**!**\xunit.runner.visualstudio.testadapter.dll!**\xunit.runner.visualstudio.dotnetcore.testadapter.dll'

- script: |
    codecov.exe -f "$(System.DefaultWorkingDirectory)/src/Snowflake.Framework.Tests/coverage.opencover.xml" -t $(codecov.secretToken)
  displayName: Publishing test coverage to Codecov 

- task: PublishCodeCoverageResults@1
  displayName: Publshing test coverage to Azure
  inputs:
    codeCoverageTool: 'cobertura' # Options: cobertura, jaCoCo
    summaryFileLocation: $(System.DefaultWorkingDirectory)/src/Snowflake.Framework.Tests/coverage.cobertura.xml

- task: PublishBuildArtifacts@1
  displayName: Publishing build artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop'