cores:
  ATARI_2600: "stella_libretro.dll"
  ATARI_5200: "stella_libretro.dll"
  ATARI_LYNX: "Atari Lynx"
  NINTENDO_NES: "nestopia_libretro.dll"
  NINTENDO_SNES: "bsnes_performance_libretro.dll"
  NINTENDO_N64: "mupen64plus_libretro.dll"
  NINTENDO_GB: "gambatte_libretro.dll"
  NINTENDO_GBC: "gambatte_libretro.dll"
  NINTENDO_GBA: "vbam_libretro.dll"
  NINTENDO_NDS: "desmume_libretro-future.dll"
  SONY_PSX: "mednafen_psx_libretro.dll"
  SEGA_SMS: "genesis_plus_gx_libretro.dll"
  SEGA_GEN: "genesis_plus_gx_libretro.dll"
  SEGA_MD: "genesis_plus_gx_libretro.dll"
  SEGA_CD: "genesis_plus_gx_libretro.dll"
  SEGA_32X: "genesis_plus_gx_libretro.dll"
  SEGA_GG: "genesis_plus_gx_libretro.dll"	